AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Resource Optimizer - Automated idle resource detection and cost optimization'

Parameters:
  NotificationEmail:
    Type: String
    Description: Email address for notifications
    Default: ''
  
  ScanSchedule:
    Type: String
    Description: Schedule for running scans (EventBridge schedule expression)
    Default: 'rate(1 day)'
  
  LogRetentionDays:
    Type: Number
    Description: CloudWatch log retention period in days
    Default: 30
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]

Resources:
  # S3 Bucket for storing reports
  ReportsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'resource-optimizer-reports-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldReports
            Status: Enabled
            ExpirationInDays: 90
            NoncurrentVersionExpirationInDays: 30

  # IAM Role for Lambda function
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'ResourceOptimizerLambdaRole-${AWS::Region}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ResourceOptimizerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Read-only access to AWS resources
              - Effect: Allow
                Action:
                  - ec2:Describe*
                  - rds:Describe*
                  - elasticloadbalancing:Describe*
                  - lambda:List*
                  - lambda:Get*
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                Resource: '*'
              
              # CloudWatch metrics access
              - Effect: Allow
                Action:
                  - cloudwatch:GetMetricStatistics
                  - cloudwatch:ListMetrics
                Resource: '*'
              
              # S3 access for reports
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetObject
                Resource: !Sub '${ReportsBucket}/*'
              
              # SNS publishing for notifications
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref NotificationTopic

  # Lambda function for resource scanning
  ResourceOptimizerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: resource-optimizer-scanner
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 900  # 15 minutes
      MemorySize: 512
      Environment:
        Variables:
          REPORTS_BUCKET: !Ref ReportsBucket
          NOTIFICATION_TOPIC: !Ref NotificationTopic
          LOG_LEVEL: INFO
      Code:
        ZipFile: |
          import json
          import boto3
          import os
          from datetime import datetime
          
          def lambda_handler(event, context):
              """
              Lambda handler for AWS Resource Optimizer.
              """
              
              print("AWS Resource Optimizer Lambda function started")
              
              # Initialize AWS clients
              s3 = boto3.client('s3')
              sns = boto3.client('sns')
              
              # Get environment variables
              reports_bucket = os.environ['REPORTS_BUCKET']
              notification_topic = os.environ['NOTIFICATION_TOPIC']
              
              try:
                  # Import and run the main scanning logic
                  # from main import main as run_scan
                  # run_scan()
                  
                  # Create sample report
                  report = {
                      'scan_timestamp': datetime.utcnow().isoformat(),
                      'total_findings': 0,
                      'total_potential_savings': 0,
                      'findings': [],
                      'status': 'completed',
                      'message': 'Infrastructure deployed successfully - upload application code to enable scanning'
                  }
                  
                  # Save report to S3
                  report_key = f"reports/{datetime.utcnow().strftime('%Y/%m/%d')}/scan-{datetime.utcnow().strftime('%H%M%S')}.json"
                  
                  s3.put_object(
                      Bucket=reports_bucket,
                      Key=report_key,
                      Body=json.dumps(report, indent=2),
                      ContentType='application/json'
                  )
                  
                  # Send notification
                  message = f"""
          AWS Resource Optimizer Scan Complete
          
          Scan Time: {report['scan_timestamp']}
          Total Findings: {report['total_findings']}
          Potential Monthly Savings: ${report['total_potential_savings']:.2f}
          
          Report Location: s3://{reports_bucket}/{report_key}
          
          Note: Upload the application code to the Lambda function to enable resource scanning.
                  """
                  
                  sns.publish(
                      TopicArn=notification_topic,
                      Subject='AWS Resource Optimizer - Scan Complete',
                      Message=message
                  )
                  
                  return {
                      'statusCode': 200,
                      'body': json.dumps({
                          'message': 'Scan completed successfully',
                          'report_location': f's3://{reports_bucket}/{report_key}'
                      })
                  }
                  
              except Exception as e:
                  print(f"Error during scan: {str(e)}")
                  
                  # Send error notification
                  sns.publish(
                      TopicArn=notification_topic,
                      Subject='AWS Resource Optimizer - Scan Failed',
                      Message=f'Scan failed with error: {str(e)}'
                  )
                  
                  return {
                      'statusCode': 500,
                      'body': json.dumps({
                          'error': str(e)
                      })
                  }

  # CloudWatch Log Group for Lambda
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ResourceOptimizerFunction}'
      RetentionInDays: !Ref LogRetentionDays

  # SNS Topic for notifications
  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: resource-optimizer-notifications
      DisplayName: AWS Resource Optimizer Notifications

  # SNS Subscription for email notifications
  EmailSubscription:
    Type: AWS::SNS::Subscription
    Condition: HasNotificationEmail
    Properties:
      Protocol: email
      TopicArn: !Ref NotificationTopic
      Endpoint: !Ref NotificationEmail

  # EventBridge rule for scheduled scanning
  ScheduledScanRule:
    Type: AWS::Events::Rule
    Properties:
      Name: resource-optimizer-schedule
      Description: Scheduled execution of AWS Resource Optimizer
      ScheduleExpression: !Ref ScanSchedule
      State: ENABLED
      Targets:
        - Arn: !GetAtt ResourceOptimizerFunction.Arn
          Id: ResourceOptimizerTarget

  # Permission for EventBridge to invoke Lambda
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ResourceOptimizerFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ScheduledScanRule.Arn

  # CloudWatch Dashboard for monitoring
  MonitoringDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: AWS-Resource-Optimizer
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/Lambda", "Duration", "FunctionName", "${ResourceOptimizerFunction}" ],
                  [ ".", "Errors", ".", "." ],
                  [ ".", "Invocations", ".", "." ]
                ],
                "period": 300,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "Lambda Function Metrics"
              }
            },
            {
              "type": "log",
              "x": 0,
              "y": 6,
              "width": 24,
              "height": 6,
              "properties": {
                "query": "SOURCE '/aws/lambda/${ResourceOptimizerFunction}'\n| fields @timestamp, @message\n| sort @timestamp desc\n| limit 100",
                "region": "${AWS::Region}",
                "title": "Recent Lambda Logs"
              }
            }
          ]
        }

Conditions:
  HasNotificationEmail: !Not [!Equals [!Ref NotificationEmail, '']]

Outputs:
  ReportsBucketName:
    Description: S3 bucket name for reports
    Value: !Ref ReportsBucket
    Export:
      Name: !Sub '${AWS::StackName}-ReportsBucket'

  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt ResourceOptimizerFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaFunction'

  NotificationTopicArn:
    Description: ARN of the SNS notification topic
    Value: !Ref NotificationTopic
    Export:
      Name: !Sub '${AWS::StackName}-NotificationTopic'

  DashboardURL:
    Description: CloudWatch Dashboard URL
    Value: !Sub 'https://${AWS::Region}.console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=AWS-Resource-Optimizer'

  DeploymentInstructions:
    Description: Next steps for full deployment
    Value: 'This template creates the infrastructure. To deploy the full application code, package and upload the Python code to the Lambda function.'